### ISSUE TITLE
There are some duplicate IndexedEventGrams

### ISSUE THREAD

**Issue by tohuynh** [CouncilDataProject/cdp-backend#145] opened 2021-12-30 19:18 UTC
### Describe the Bug

The top five IndexedEventGrams for an event contain duplicates. (There is a couple of examples of this at https://tohuynh.github.io/cdp-frontend/#/events for seattle-staging database).

For example, for this event:
![image](https://user-images.githubusercontent.com/37560480/147781156-f6824352-672a-42a9-8a32-346bae31e30b.png)
`zoo` and `animals` are duplicates. The duplicates are exactly the same except for the values of `datetime_weighted_value`, `value`, and `id`.

### Expected Behavior

There should be no duplicates IndexedEventGrams. 

![image](https://user-images.githubusercontent.com/37560480/147781632-1404e3ab-4f01-4c63-89d7-3d8bca77461b.png)

I checked the top 20 IndexedEventGrams  for the event, my guess is that the old IndexedEventGrams aren't being updated with new `datetime_weighted_value` and `value`, instead, new ones are created and the old ones aren't deleted.

cc @JacksonMaxfield

**Comment by JacksonMaxfield** [comment] 2022-01-06 04:23
Since this is a datetime thing I _think_ this may have had to do with the hashing fix that just went through. I will keep this open for now but if we don't see this behavior in a couple of weeks I think we can close it.

**Comment by JacksonMaxfield** [comment] 2022-01-13 01:53
I think this was caused by the datetime hashing bug. Going to close this now but we can reopen if it crops up again.

**Closed by JacksonMaxfield** 2022-01-13 01:53 UTC
Labels: bug
